// 창작 활동을 위한 형용사와 명사 리스트

class WordLists {
  // Tech & New Media + Classic Artistic 형용사들
  static const List<String> adjectives = [
    // Tech & New Media
    'Interactive',
    'Generative',
    'Kinetic',
    'Immersive',
    'Experimental',
    'Responsive',
    'Procedural',
    'Data-driven',
    'Algorithmic',
    'Bio-inspired',
    'AI-powered',
    'Sensor-based',
    'Glitchy',
    'Pixel-perfect',
    'Real-time',
    'Crowd-sourced',
    'Augmented',
    'Networked',
    'Open-source',
    'Sustainable',
    'Mysterious',
    'Vibrant',
    'Minimalist',
    'Abstract',
    'Surreal',
    'Cosmic',
    'Nostalgic',
    'Futuristic',
    'Organic',
    'Geometric',
    'Dreamy',
    'Dramatic',
    'Peaceful',
    'Chaotic',
    'Elegant',
    'Bold',
    'Subtle',
    'Vintage',
    'Modern',
    'Whatever',
    // Fun additions
    'Bizarre',
    'Whimsical',
    'Epic',
    'Funky',
    'Weird',
    'Magical',
    'Spooky',
    'Hilarious',
    'Ridiculous',
    'Absurd',
    'Playful',
    'Silly',
    'Random',
    'Unexpected',
    'Mind-blowing',
  ];

  static const List<String> nouns = [
    'Media Art',
    'Arduino Project',
    'IoT Device',
    'Mobile App',
    'VR Project',
    'AR Filter',
    'Interactive Website',
    'Generative Art',
    'Sound Visualization',
    'LED Matrix',
    'Motion Sensor',
    'Chatbot',
    'Data Visualization',
    'NFT Collection',
    'Game Prototype',
    'Neural Network',
    'Blockchain Project',
    'AI Video',
    'Board Game',
    'Mobile Game',
    'PC Game',
    'Art Book',
    'TouchDesigner Project',
    'Something Physical',
    'Whatever You Want',
    // Fun additions
    'Something That Moves',
    'Thing That Nobody Uses',
    'Object From The Future',
    'Item That Shouldn\'t Exist',
    'Useless But Beautiful Thing',
    'Something You Can\'t Touch',
    'Device That Does Nothing',
    'Object That Changes Color',
    'Thing That Makes Sound',
    'Something Completely Random',
    'Item That Tells Stories',
    'Object That Brings Joy',
    'Thing That Confuses People',
    'Something Everyone Needs',
    'Item That Breaks Rules',
  ];

  // 발표자 리스트 (예시 - 실제 사용할 이름으로 변경 가능)
  static const List<String> presenters = [
    'Eunseo Park',
    'Yoonmyung Kim',
    'Joonheon Min',
    'Soojeong Han',
  ];
}
